spring:
  application:
    name: handsome
  profiles:
    active: dev

server:
  port: 8190

# 日志配置
logging:
  level:
    # 隐藏Spring事务管理相关的调试日志
    org.springframework.jdbc.datasource.DataSourceTransactionManager: WARN
    # 隐藏MyBatis会话管理日志
    org.apache.ibatis.transaction: WARN
    org.mybatis.spring: WARN
    # 如果你想完全隐藏SQL日志，可以设置为WARN
    # com.fyp.handsome.mapper: WARN
    # 保持你的业务日志为INFO级别
    com.fyp.handsome: INFO
    root: INFO

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键策略 - 自增
      id-type: auto
      # 逻辑删除字段
      logic-delete-field: deleted
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  # Mapper XML 文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: com.fyp.handsome.entity 

# 阿里云配置
aliyun:
  # 访问密钥ID（建议使用环境变量 ALIBABA_CLOUD_ACCESS_KEY_ID）
  access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID:}
  # 访问密钥Secret（建议使用环境变量 ALIBABA_CLOUD_ACCESS_KEY_SECRET）
  access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET:}
  # 地域
  region: cn-beijing
  # API端点
  endpoint: quanmiaolightapp.cn-beijing.aliyuncs.com
  # 工作空间ID
  workspace-id: llm-f3b251bxpv09yaq9
  # 视频分析模型ID
  video-model-id: qwen-vl-max-latest 